# Generated by Django 5.0.7 on 2024-07-28 13:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StopLoss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_price", models.FloatField()),
                ("limit_price", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TakeProfit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("limit_price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_id", models.UUIDField(default=uuid.UUID, editable=False)),
                ("symbol", models.CharField(max_length=255)),
                ("notional", models.FloatField(blank=True, null=True)),
                ("qty", models.FloatField(blank=True, null=True)),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("market", "market"),
                            ("limit", "limit"),
                            ("stop", "stop"),
                            ("stop_limit", "stop_limit"),
                            ("trailing_stop", "trailing_stop"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("buy", "buy"), ("sell", "sell")], max_length=255
                    ),
                ),
                (
                    "time_in_force",
                    models.CharField(
                        choices=[
                            ("day", "day"),
                            ("gtc", "gtc"),
                            ("opg", "opg"),
                            ("cls", "cls"),
                            ("ioc", "ioc"),
                            ("fok", "fok"),
                        ],
                        max_length=255,
                    ),
                ),
                ("extended_hours", models.BooleanField(blank=True, null=True)),
                (
                    "client_order_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "order_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("simple", "simple"),
                            ("bracket", "bracket"),
                            ("oco", "oco"),
                            ("oto", "oto"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "position_intent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("buy_to_open", "buy_to_open"),
                            ("buy_to_close", "buy_to_close"),
                            ("sell_to_open", "sell_to_open"),
                            ("sell_to_close", "sell_to_close"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "stop_loss",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="router.stoploss",
                    ),
                ),
                (
                    "take_profit",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="router.takeprofit",
                    ),
                ),
            ],
        ),
    ]
