# Generated by Django 5.0.7 on 2024-07-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("router", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bracket", "bracket"),
                    ("oco", "oco"),
                    ("oto", "oto"),
                    ("simple", "simple"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="position_intent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("buy_to_close", "buy_to_close"),
                    ("buy_to_open", "buy_to_open"),
                    ("sell_to_close", "sell_to_close"),
                    ("sell_to_open", "sell_to_open"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="time_in_force",
            field=models.CharField(
                choices=[
                    ("gtc", "gtc"),
                    ("day", "day"),
                    ("opg", "opg"),
                    ("cls", "cls"),
                    ("ioc", "ioc"),
                    ("fok", "fok"),
                ],
                max_length=255,
            ),
        ),
    ]
