# Generated by Django 5.0.7 on 2024-07-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("router", "0002_alter_order_order_class_alter_order_position_intent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="asset_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="symbol",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
